# Generated by Django 4.1.2 on 2022-10-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["name"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="is_key_skills",
            new_name="is_key_skill",
        ),
    ]
